repos:
  - repo: local #https://github.com/pre-commit/pre-commit-hooks
    # rev: v4.0.1
    hooks:
      - id: format-code
        name: Run black
        language: system
        types: [python]
        entry: black

      - id: lint-python-code
        args: ['--max-line-length=88', '--extend-ignore=E205, W503, W605', '--exclude=.venv']
        name: Run flake8
        description: 'Apply a lintern to python code'
        entry: flake8
        language: system
        types: [python]
      
      - id: isort
        args: ['--profile=black']
        name: Run isort
        entry: isort
        language: system
        types: [python]

      - id: pydocstyle
        args: ['--convention=google', '--add-ignore=D100, D101, D102, D103, D104, D105, D106, D107']
        name: Run pydocstyle
        entry: pydocstyle
        language: system
        types: [python]